### ISSUE TITLE
error when installing your build

### ISSUE THREAD

**Issue by wmzaru** [BlackScorpGames/logd#1]
After installing the turn to home site.cc / home.php 
Generates this error.
![error](https://cloud.githubusercontent.com/assets/859515/4644743/79f548f4-545f-11e4-9a77-b9c9f7e00fe2.jpg)

**Comment by BlackScorp** [comment]
hey, i use composer there to install libraries you need to download the https://getcomposer.org/download/ Composer-Setup.exe after installation just right click on your folder an call update.

Composer is similar to an Appstore but for PHP Packages

**Comment by BlackScorp** [comment]
i will restart everything over so that the script should work with php 7.1
