### ISSUE TITLE
Repeating error in /lib/http.php

### ISSUE THREAD

**Issue by flamablecharlie** [BlackScorpGames/logd#2]
I'm getting a very unusual error in the http.php library.

Here's an example:
`2016/11/14 16:09:27 [error] 6022#0: *1862 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Http' not found in /var/www/lotgd/lib/http.php on line 5" while reading response header from upstream, client: xx.xxx.xx.xxx, server: mygame.com, request: "GET /runmodule.php?module=pool&c=36-160924 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mygame.com", referrer: "http://mygame.com/village.php?c=35-160920"`

The problem is, it's not just the pool module. It happens with ANY module I install and activate. Once they're active, anyone tries accessing them, everything crashes to a halt because of that specific line in /lib/http.php.

`$httpClass = new Http();`

Any ideas on fixing this?

**Comment by BlackScorp** [comment]
closing this issue since its old and i will start over soon with this project again
